language: go
go:
    - 1.4
env:
    - "PATH=/home/travis/gopath/bin:$PATH"
before_script:
    - psql -c 'create database triage_test;' -U postgres
before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
script:
    - go test -v -covermode=count -coverprofile=coverage.out ./triage
    - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
    - go build -v ./...
