ALTER TABLE ticket ADD COLUMN status_id INT(11) UNSIGNED  NOT NULL DEFAULT 1;
ALTER TABLE ticket ADD CONSTRAINT ticket_status FOREIGN KEY (status_id) REFERENCES status (id) ON DELETE NO ACTION ON UPDATE CASCADE;
