// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ticket.proto

/*
Package ticketpb is a generated protocol buffer package.

It is generated from these files:
	ticket.proto

It has these top-level messages:
	Ticket
	ListRequest
	ListResponse
	CreateRequest
	CreateResponse
*/
package ticketpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ticket struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
}

func (m *Ticket) Reset()                    { *m = Ticket{} }
func (m *Ticket) String() string            { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()               {}
func (*Ticket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ticket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListResponse struct {
	Tickets []*Ticket `protobuf:"bytes,1,rep,name=tickets" json:"tickets,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetTickets() []*Ticket {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type CreateRequest struct {
	Subject string `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type CreateResponse struct {
	Ticket *Ticket `protobuf:"bytes,1,opt,name=ticket" json:"ticket,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateResponse) GetTicket() *Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func init() {
	proto.RegisterType((*Ticket)(nil), "ticketpb.Ticket")
	proto.RegisterType((*ListRequest)(nil), "ticketpb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ticketpb.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "ticketpb.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "ticketpb.CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TicketService service

type TicketServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type ticketServiceClient struct {
	cc *grpc.ClientConn
}

func NewTicketServiceClient(cc *grpc.ClientConn) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/ticketpb.TicketService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/ticketpb.TicketService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TicketService service

type TicketServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterTicketServiceServer(s *grpc.Server, srv TicketServiceServer) {
	s.RegisterService(&_TicketService_serviceDesc, srv)
}

func _TicketService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticketpb.TicketService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticketpb.TicketService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticketpb.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TicketService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TicketService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket.proto",
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0x86, 0x30,
	0x10, 0x86, 0x2d, 0x9a, 0x7e, 0x7a, 0xdf, 0x07, 0x31, 0x97, 0xa8, 0x0d, 0x13, 0xe9, 0x84, 0x0e,
	0x0c, 0x38, 0x98, 0x90, 0x38, 0xb9, 0x3a, 0xa1, 0x7f, 0x40, 0xe0, 0x86, 0x6a, 0x22, 0x48, 0x8b,
	0x7f, 0xc1, 0xbf, 0x6d, 0xec, 0xd1, 0x00, 0xea, 0xd6, 0x7b, 0xef, 0xbd, 0xf7, 0xb9, 0x4b, 0xe1,
	0xe0, 0x4c, 0xfb, 0x46, 0xae, 0x18, 0xc6, 0xde, 0xf5, 0x78, 0xca, 0xd5, 0xd0, 0xe8, 0x12, 0xe4,
	0xb3, 0x7f, 0x63, 0x02, 0x91, 0xe9, 0x94, 0xc8, 0x44, 0x7e, 0x56, 0x47, 0xa6, 0x43, 0x05, 0x3b,
	0x3b, 0x35, 0xaf, 0xd4, 0x3a, 0x15, 0x79, 0x31, 0x94, 0x3a, 0x86, 0xfd, 0xa3, 0xb1, 0xae, 0xa6,
	0x8f, 0x89, 0xac, 0xd3, 0x15, 0x1c, 0xb8, 0xb4, 0x43, 0xff, 0x6e, 0x09, 0x6f, 0x60, 0xc7, 0xf1,
	0x56, 0x89, 0xec, 0x38, 0xdf, 0x97, 0xe7, 0x45, 0xc0, 0x15, 0xcc, 0xaa, 0x83, 0x41, 0x5f, 0x43,
	0xfc, 0x30, 0xd2, 0x8b, 0xa3, 0x39, 0x6c, 0x4d, 0x15, 0x5b, 0x6a, 0x05, 0x49, 0xb0, 0xce, 0xa0,
	0x1c, 0x24, 0xe7, 0x78, 0xeb, 0x7f, 0x9c, 0xb9, 0x5f, 0x7e, 0x09, 0x88, 0x59, 0x7a, 0xa2, 0xf1,
	0xd3, 0xb4, 0x84, 0x77, 0x70, 0xf2, 0xb3, 0x34, 0x5e, 0x2c, 0x33, 0xab, 0x9b, 0xd2, 0xcb, 0xdf,
	0x32, 0x23, 0xf5, 0x11, 0xde, 0x83, 0xe4, 0x35, 0xf0, 0x6a, 0xf1, 0x6c, 0x6e, 0x48, 0xd5, 0xdf,
	0x46, 0x18, 0x6f, 0xa4, 0xff, 0x80, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x18, 0x1d,
	0x29, 0x90, 0x01, 0x00, 0x00,
}
